#! /bin/sh

######## For RPi, some of the /extras scripts prefer config files in /boot,
######## where they can be easily edited on a foreign host.
if [ "$ID" = "raspbian" ] ; then
  if [ ! -f /boot/derbynet.conf ] ; then
    cp /usr/local/bin/derbynet/derbynet.conf /boot
  fi
fi
