#!/bin/sh

TIMER_ARGS=

test -f /etc/derbynet.conf  && . /etc/derbynet.conf
test -f /boot/derbynet.conf  && . /boot/derbynet.conf
test -f /usr/local/bin/derbynet/timer/derbynet.conf && . /usr/local/bin/derbynet/timer/derbynet.conf

# Wait for server and network to come up
CONTACT_OK=0
while [ $CONTACT_OK -eq 0 ]; do
    echo Attempting to contact $DERBYNET_SERVER
    curl --insecure --connect-timeout 6 --location --silent \
         "$DERBYNET_SERVER/index.php" > /dev/null && \
        CONTACT_OK=1
done
echo Starting timer jar

sudo /usr/bin/java -jar /usr/local/bin/derbynet/timer/derby-timer.jar $TIMER_ARGS $DERBYNET_SERVER
