
name: JPackage Win

on: 
  workflow_dispatch:
    inputs:
      jar_url:
        description: 'URL for retrieving derby-timer.jar file.'
        required: true

jobs:
  jpackage_win:
    runs-on: windows-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: tempdir
      run: mkdir tempdir

    - name: Download jar
      run: curl -s -S --output tempdir\derby-timer.jar "${{ github.event.inputs.jar_url }}"

      # Windows jpackage offers these types: app-image, exe, msi
    - name: jpackage msi
      run: >
        jpackage
        --type msi
        --name derby-timer
        --verbose 
        --input tempdir
        --main-jar derby-timer.jar
        --main-class org.jeffpiazza.derby.TimerMain

    - name: upload msi
      uses: actions/upload-artifact@v2
      with:
        name: windows-msi
        path: derby-timer*.msi

    - name: look around
      run: dir

    - name: clean up msi
      run: del derby-timer*.msi

    - name: jpackage app-image
      run: >
        jpackage
        --type app-image
        --name derby-timer
        --verbose 
        --input tempdir
        --main-jar derby-timer.jar
        --main-class org.jeffpiazza.derby.TimerMain

    - name: upload app-image
      uses: actions/upload-artifact@v2
      with:
        name: windows-app-image
        path: derby-timer*
